laravel/framework:
  source:
    type: git
    url: https://github.com/laravel/framework.git
    reference: master
  install:
    - composer update --prefer-dist --no-interaction --prefer-stable --no-suggest
    - echo -e "\nREDIS_HOST=localhost\nREDIS_PORT=6379" >> .env
